//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziYorumProje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblYorum
    {
        public int Yorumid { get; set; }
        public string KullaniciAd { get; set; }
        public string Mail { get; set; }
        public string Yorumicerik { get; set; }
        public Nullable<int> YorumBlok { get; set; }
    
        public virtual TblBlok TblBlok { get; set; }
    }
}
